### PR TITLE
Merge 0-1-stable from mdsol/crichton into mdsol-share/crichton develop

### PR DESCRIPTION
**Pull request by csavage-mdsol**
Title says it all! Syncing the private version of Crichton with the public.

### CODE REVIEW

**Comment by HonoreDB** [comment]
Going to do what I should've done with the Representors PR and leave it up for a bit for others to comment. (Sorry in advance Andrei that we didn't really live up to your vision for making the transition smoother).

**Comment by csavage-mdsol** [comment]
Ah, good call.  Do you want to give a brief synopsis of the changes?

**Comment by HonoreDB** [comment]
Super briefly, this refactors Crichton to use Representors for json serialization, and adds integration tests with a copy of Crichton Demo Service.

**Comment by csavage-mdsol** [comment]
@HonoreDB doesn't look like comments are forthcoming.

**Pull request merged**
